
# https://quarto.org/docs/websites/website-navigation.html#side-navigation
project:
  type: website

website:

  title: "Bonsai.jl"
  description: Bonsai.jl Documentation
  repo-url: https://github.com/onetonfoot/Bonsai.jl
  repo-branch: master
  repo-actions: [issue]

  sidebar: 
    search: true
    contents: 
      - "index.qmd"
      - "handlers.qmd"
      - "middleware.qmd"
      - "examples.qmd"
      - "open_api.qmd"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



